baseurl: "https://semilla.com/"
DefaultContentLanguage: "es"
languageCode: "es-ar"
title: "Inicio"
params:
  description: El slogan
  images:
  - '/img/quilt2.png'
  title: Chuncane
googleAnalytics: 
