backend:
  name: git-gateway

media_folder: "site/static/img" # Folder where user uploaded files should go
public_folder: "img"

collections: # A list of collections the CMS should be able to edit
  - name: "post" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "Post" # Used in the UI, ie.: "New Post"
    folder: "site/content/post" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    fields: # The fields each document in this collection have
      - {label: "Título", name: "title", widget: "string"}
      - {label: "Fecha de publicación", name: "date", widget: "datetime"}
      - {label: "Intro", name: "description", widget: "text"}
      - {label: "Imagen", name: "image", widget: "image", required: false}
      - {label: "Contenido", name: "body", widget: "markdown"}
  - name: "poi" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "Poi" # Used in the UI, ie.: "New Post"
    folder: "site/content/poi" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    fields: # The fields each document in this collection have
      - {label: "Titulo", name: "title", widget: "hidden", default: {{location.name}}}
      - {label: "Frase", name: "description", widget: "string"}
      - {label: "Imagen", name: "image", widget: "image", required: false}
      - {label: "Email", name: "email", widget: "text"}
      - {label: "Facebook", name: "facebook", widget: "text"}
      - {label: "Instagram", name: "instagram", widget: "text"}
      - {label: "Twitter", name: "twitter", widget: "text"}
      - {label: "Web", name: "web", widget: "text"}
      - label: "Ubicacion"
        name: "location"
        widget: "object"
        fields:
          - {label: "Type", name: "@type", widget: "hidden", default: "Place"}
          - {label: "Nombre", name: "name", widget: "string"}
          - label: "Direccion"
            name: "address"
            widget: "object"
            fields: 
              - {label: "Type", name: "@type", widget: "hidden", default: "PostalAddress"}
              - {label: "Calle y numero", name: "streetAddress", widget: "text"}
              - {label: "Localidad", name: "addressLocality", widget: "text"}
              - {label: "Codigo postal", name: "postalCode", widget: "text"}
              - label: "Provincia"
                name: "addressRegion"
                widget: "select"
                options: ["Cordoba", "San Luis"]
              - {label: "Address Country", name: "addressCountry", widget: "hidden", default: "AR"}
  - name: "artist" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "Artista" # Used in the UI, ie.: "New Post"
    folder: "site/content/artist" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    fields: # The fields each document in this collection have
      - {label: "Titulo", name: "title", widget: "hidden", default: {{name}} {{lastname}}}
      - {label: "Nombre", name: "name", widget: "string"}
      - {label: "Apellido", name: "lastname", widget: "string"}
      - {label: "Avatar", name: "avatar", widget: "image", required: false}
      - {label: "Bio", name: "bio", widget: "markdown"}
      - {label: "Pueblo", name: "town", widget: "string"}
      - {label: "Email", name: "email", widget: "text"}
      - {label: "Facebook", name: "facebook", widget: "text", required: false}
      - {label: "Instagram", name: "instagram", widget: "text", required: false}
      - {label: "Twitter", name: "twitter", widget: "text", required: false}
      - {label: "Web", name: "web", widget: "text", required: false}
      - {label: "Performer Type", name: "performerType", widget: "select", options: ["PerformingGroup", "Person"] 
      - {label: "Performer Name", name: "performerName", widget: "hidden", default: {{title}}}
  - name: "event" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "Evento" # Used in the UI, ie.: "New Post"
    folder: "site/content/event" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    fields: # The fields each document in this collection have
      - {label: "Title", name: "title", widget: "string"}
      - label: "Location"
        name: "location"
        widget: "relation"
        collection: "poi"
        valueField: "title"
      - {label: "Name", name: "name", widget: "text"}
      - {label: "Start Date", name: "startDate", widget: "datetime", format: "LLLL"}
      - {label: "Description", name: "description", widget: "text"}
      - label: "Performer"
        name: "performer"
        widget: "relation"
        collection: "artist"
        valueField: "title"
  - name: "pages"
    label: "Pages"
    files:
      - file: "site/content/_index.md"
        label: "Home Page"
        name: "home"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Subtitle, name: subtitle, widget: string}
          - {label: Image, name: image, widget: image}
          - {label: "Blurb", name: blurb, widget: object, fields: [
              {label: "Heading", name: "heading", widget: string},
              {label: "Text", name: "text", widget: "text"}]}
          - {label: "Intro", name: intro, widget: object, fields: [
              {label: "Heading", name: "heading", widget: string},
              {label: "Text", name: "text", widget: "text"}]}
          - {label: "Products", name: products, widget: list, fields: [
              {label: "Image", name: "image", widget: "image"},
              {label: "Text", name: "text", widget: "text"}]}
          - {label: "Values", name: "values", widget: "object", fields: [
              {label: "Heading", name: "heading", widget: string},
              {label: "Text", name: "text", widget: "text"}]}
