backend:
  name: git-gateway

media_folder: "site/static/img" # Folder where user uploaded files should go
public_folder: "img"

collections: # A list of collections the CMS should be able to edit
  - name: "post" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "Post" # Used in the UI, ie.: "New Post"
    folder: "site/content/post" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    fields: # The fields each document in this collection have
      - {label: "Título", name: "title", widget: "string"}
      - {label: "Fecha de publicación", name: "date", widget: "datetime"}
      - {label: "Intro", name: "description", widget: "text"}
      - {label: "Imagen", name: "image", widget: "image", required: false}
      - {label: "Contenido", name: "body", widget: "markdown"}
  - name: "poi" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "Poi" # Used in the UI, ie.: "New Post"
    folder: "site/content/poi" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    fields: # The fields each document in this collection have
      - {label: "Nombre", name: "name", widget: "string"}
      - {label: "Dirección", name: "adress", widget: "string"}
      - {label: "Pueblo", name: "town", widget: "string"}
      - {label: "Frase", name: "tagline", widget: "string"}
      - {label: "Horario", name: "open", widget: "string"}
      - {label: "Descripción", name: "description", widget: "text"}
      - {label: "Imagen", name: "image", widget: "image", required: false}
      - {label: "Contenido", name: "body", widget: "markdown"}
      - {label: "Email", name: "email", widget: "text"}
      - {label: "Facebook", name: "facebook", widget: "text"}
      - {label: "Instagram", name: "instagram", widget: "text"}
      - {label: "Twitter", name: "twitter", widget: "text"}
      - {label: "Web", name: "web", widget: "text"}
  - name: "artist" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "Artista" # Used in the UI, ie.: "New Post"
    folder: "site/content/artist" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    fields: # The fields each document in this collection have
      - {label: "Nombre", name: "name", widget: "string"}
      - {label: "Apellido", name: "lastname", widget: "string"}
      - {label: "Avatar", name: "avatar", widget: "image", required: false}
      - {label: "Bio", name: "bio", widget: "markdown"}
      - {label: "Pueblo", name: "town", widget: "string"}
      - {label: "Frase", name: "tagline", widget: "string"}
      - {label: "Email", name: "email", widget: "text"}
      - {label: "Facebook", name: "facebook", widget: "text", required: false}
      - {label: "Instagram", name: "instagram", widget: "text", required: false}
      - {label: "Twitter", name: "twitter", widget: "text", required: false}
      - {label: "Web", name: "web", widget: "text", required: false}
  - name: "event" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "Evento" # Used in the UI, ie.: "New Post"
    folder: "site/content/event" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    fields: # The fields each document in this collection have
      - {label: "Title", name: "title", widget: "text"}
      - label: "Location"
        name: "location"
        widget: "object"
        fields:
          - {label: "Type", name: "@type", widget: "hidden", default: "Place"}
          - {label: "Name", name: "name", widget: "text"}
          - label: "Address"
            name: "adress"
            widget: "object"
            fields: 
              - {label: "Type", name: "@type", widget: "hidden", default: "PostalAddress"}
              - {label: "Street Address", name: "streetAddress", widget: "text"}
              - {label: "Address Locality", name: "addressLocality", widget: "text"}
              - {label: "Postal Code", name: "postalCode", widget: "text"}
              - {label: "Address Region", name: "addressRegion", widget: "text"}
              - {label: "Address Country", name: "addressCountry", widget: "hidden", default: "AR"}
      - {label: "Name", name: "name", widget: "text"}
      - {label: "Start Date", name: "startDate", widget: "datetime"}
      - {label: "Description", name: "description", widget: "text"}
      - label: "Performer"
        name: "performer"
        widget: "object"
        fields:
          - {label: "Performer Type", name: "performerType", widget: "select", options: ["PerformingGroup", "Person"]} 
          - {label: "Performer Name", name: "performerName", widget: "text"}
  - name: "pages"
    label: "Pages"
    files:
      - file: "site/content/_index.md"
        label: "Home Page"
        name: "home"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Subtitle, name: subtitle, widget: string}
          - {label: Image, name: image, widget: image}
          - {label: "Blurb", name: blurb, widget: object, fields: [
              {label: "Heading", name: "heading", widget: string},
              {label: "Text", name: "text", widget: "text"}]}
          - {label: "Intro", name: intro, widget: object, fields: [
              {label: "Heading", name: "heading", widget: string},
              {label: "Text", name: "text", widget: "text"}]}
          - {label: "Products", name: products, widget: list, fields: [
              {label: "Image", name: "image", widget: "image"},
              {label: "Text", name: "text", widget: "text"}]}
          - {label: "Values", name: "values", widget: "object", fields: [
              {label: "Heading", name: "heading", widget: string},
              {label: "Text", name: "text", widget: "text"}]}
      - file: "site/content/contact/_index.md"
        label: "Contact Page"
        name: "contact"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Logo, name: logo, widget: image}
          - {label: Body, name: body, widget: markdown}
          - label: Contact Entries
            name: contact_entries
            widget: list
            fields:
              - label: Heading
                name: heading
                widget: string
              - label: Text
                name: text
                widget: text
      - file: "site/content/products/_index.md"
        label: "Products Page"
        name: "products"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Image, name: image, widget: image}
          - {label: Heading, name: heading, widget: string}
          - {label: Description, name: description, widget: string}
          - {label: Intro, name: intro, widget: object, fields: [{label: Heading, name: heading, widget: string}, {label: Description, name: description, widget: text}, {label: Blurbs, name: blurbs, widget: list, fields: [{label: Image, name: image, widget: image}, {label: Text, name: text, widget: text}]}]}
          - {label: Main, name: main, widget: object, fields: [{label: Heading, name: heading, widget: string}, {label: Description, name: description, widget: text}, {label: Image1, name: image1, widget: object, fields: [{label: Image, name: image, widget: image}, {label: Alt, name: alt, widget: string}]}, {label: Image2, name: image2, widget: object, fields: [{label: Image, name: image, widget: image}, {label: Alt, name: alt, widget: string}]}, {label: Image3, name: image3, widget: object, fields: [{label: Image, name: image, widget: image}, {label: Alt, name: alt, widget: string}]}]}
          - {label: Testimonials, name: testimonials, widget: list, fields: [{label: Quote, name: quote, widget: string}, {label: Author, name: author, widget: string}]}
          - {label: Full_image, name: full_image, widget: image}
          - {label: Pricing, name: pricing, widget: object, fields: [{label: Heading, name: heading, widget: string}, {label: Description, name: description, widget: string}, {label: Plans, name: plans, widget: list, fields: [{label: Plan, name: plan, widget: string}, {label: Price, name: price, widget: string}, {label: Description, name: description, widget: string}, {label: Items, name: items, widget: list}]}]}
      - file: "site/content/values/_index.md"
        label: "Values Page"
        name: "values"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Image, name: image, widget: image}
          - label: Values
            name: values
            widget: list
            fields:
              - {label: Heading, name: heading, widget: string}
              - {label: Text, name: text, widget: text}
              - {label: Image, name: imageUrl, widget: image}
