backend:
  name: git-gateway

media_folder: "site/static/img" # Folder where user uploaded files should go
public_folder: "img"

collections: # A list of collections the CMS should be able to edit
  - name: "tema"
    label: "Temas"
    folder: "site/content/temas"
    create: true
    fields: 
      - {label: "Título", name: "title", widget: "string"}
      - {label: "Archivo", name: "file", widget: "file"}
      - {label: "Proyecto", name: "project", widget: "string"}
